trailingComma: 'all'
singleQuote: true
printWidth: 100
bracketSpacing: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder: ['./instrument', 'react', '<THIRD_PARTY_MODULES>', '^(?!.*\.css$)[./].*$', '.css$']
