trailingComma: 'all'
singleQuote: true
printWidth: 100
bracketSpacing: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - '@babel/plugin-syntax-import-assertions'
importOrder:
  - '^@core/(.*)$'
  - '^@server/(.*)$'
  - '^@ui/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
overrides:
  - files: '*.{ts,tsx}'
    options:
      parser: 'typescript'
