# This GitHub Action builds the Docker image for the Next.js application,
# runs the Docker container, performs a health check to ensure the application
# is running correctly, and then stops and removes the container. This action
# is exclusively triggered via workflow dispatch.

name: Test and Publish Docker Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --build-arg NEXT_PUBLIC_PROMPTFOO_BASE_URL=http://localhost:3000 -t promptfoo-ui:ci .

      - name: Tag Docker image
        run: docker tag promptfoo-ui:ci your-dockerhub-username/promptfoo-ui:latest

      - name: Run Docker container
        run: |
          # Start the Docker container in detached mode
          docker run -d --name promptfoo-container -p 3000:3000 promptfoo-ui:ci

          # Loop to check if the server is up
          for i in {1..10}; do
            if curl -f http://localhost:3000/health; then
              echo -e "\nHealth check passed"
              HEALTH_CHECK_PASS=true
              break
            else
              echo "Health check failed, retrying in 2 seconds..."
              sleep 2
            fi
          done

          # If health check did not pass after retries, exit with an error
          if [ -z "$HEALTH_CHECK_PASS" ]; then
            echo -e "\nHealth check failed after multiple attempts" >&2
            docker stop promptfoo-container
            docker rm promptfoo-container
            exit 1
          fi

          # Stop and remove the Docker container
          docker stop promptfoo-container
          docker rm promptfoo-container

      - name: Push Docker image to DockerHub
        run: docker push ghcr.io/promptfoo/promptfoo:latest
